### ISSUE TITLE
Deny rewards for subgraph deployments using the new subgraph composition feature

### ISSUE THREAD

**Issue by fordN** [graphprotocol/subgraph-oracle#32]
Until the feature is ratified for indexing rewards support the subgraph-oracle should deny rewards for any deployment using it. 

DataSources using this feature will have `kind` = `subgraph`. 

### Example
Datasource exert from manifest:
```dataSources:
  - kind: subgraph
    name: Factory
    network: scroll
    source:
      address: 'QmdXu8byAFCGSDWsB5gMQjWr6GUvEVB7S1hemfxNuomerz'
      startBlock: 82522```

**Comment by incrypto32** [comment]
Looks like there is nothing to be done here since its based on an allowlist of data source kinds. Since we dont have the `subgraph` kind in the allow list of datasource kinds we will deny rewards automatically for them

https://github.com/graphprotocol/subgraph-oracle/blob/28312fd0a4895827aaa95c0f0ba151c488080e8b/availability-oracle/src/main.rs#L545-L548
